version: '3'

services:
  server1:
    build: ./server
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
    volumes:
      - ./server:/app

  server2:
    build: ./server
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
    volumes:
      - ./server:/app

  server3:
    build: ./server
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
    volumes:
      - ./server:/app

  server4:
    build: ./server
    ports:
      - "3005:3000"
    environment:
      - PORT=3000
    volumes:
      - ./server:/app

  server5:
    build: ./server
    ports:
      - "3006:3000"
    environment:
      - PORT=3000
    volumes:
      - ./server:/app

  client1:
    build: ./client
    ports:
      - "3007:3000"
    volumes:
      - ./client:/app

  client2:
    build: ./client
    ports:
      - "3008:3000"
    volumes:
      - ./client:/app

  client3:
    build: ./client
    ports:
      - "3009:3000"
    volumes:
      - ./client:/app

  client4:
    build: ./client
    ports:
      - "3010:3000"
    volumes:
      - ./client:/app

  client5:
    build: ./client
    ports:
      - "3011:3000"
    volumes:
      - ./client:/app
